apiVersion: v1
kind: ServiceAccount
metadata:
  name: python-app-sa
  namespace: python-app
  annotations:
    # This annotation links the Kubernetes service account to the Azure managed identity
    # The CSI driver and Workload Identity use this to authenticate to Azure
    azure.workload.identity/client-id: "ecc6715e-6a59-41ee-899c-1f19de613457"
  labels:
    # Label required for Workload Identity webhook to inject identity
    azure.workload.identity/use: "true"