apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Base resources
resources:
  - ../../base

# Namespace for prod environment
namespace: python-app-prod

# Patches for prod-specific settings
patches:
  # Patch deployment for prod-specific settings
  - target:
      kind: Deployment
      name: python-app
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3

# Patch ConfigMap for prod-specific config
  - target:
      kind: ConfigMap
      name: python-app-config
    patch: |-
      - op: replace
        path: /data/APP_ENV
        value: production
      - op: replace
        path: /data/DEBUG_MODE
        value: "false"
      - op: replace
        path: /data/LOG_LEVEL
        value: WARNING
      - op: add
        path: /data/MAX_CONNECTIONS
        value: "1000"